version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  build: 
    commands:
      - cd HelloWorldDemo
      - mvn clean 
      # skipping the tests while packaging
      - mvn -Dmaven.test.skip package

  post_build:
    commands:
      - ls target/
      - aws lambda update-function-code --function-name  javademo --zip-file fileb://target/demo-1.0.0.jar --region ap-south-1
